package com.skylvr.sample.dynamo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.io.Serializable;


@DynamoDBTable(tableName = "employee")
@Data
public class Employee implements Serializable {
    private static final long serialVersionUID = 1L;
    @DynamoDBHashKey(attributeName = "employeeId")
    @DynamoDBAutoGeneratedKey
    String employeeId;
    @DynamoDBAttribute
    String firstName;
    @DynamoDBAttribute
    String lastName;
    @DynamoDBRangeKey
    String email;
    @DynamoDBAttribute
    int age;
    Address address;

}
